SET HEAD OFF VERIFY OFF
SET LONG 1000000

SELECT DECODE(B.LINE, 1, 'CREATE OR REPLACE ','') || B.TEXT
  FROM USER_PROCEDURES A,USER_SOURCE B
 WHERE A.OBJECT_NAME = '&1'
   AND A.OBJECT_NAME = B.NAME;
